const actionTypes = {
  SELECT_PIECE: "SELECT_PIECE",
  NEW_MOVE: "NEW_MOVE",
  INVALID_MOVE: "INVALID_MOVE",
  IS_CHECKED: "IS_CHECKED",
  TAKE_BACK: "TAKE_BACK",
  // GENERATE_CANDIDATE_MOVES: "GENERATE_CANDIDATE_MOVES",
  // CLEAR_CANDIDATES: "CLEAR_CANDIDATES",
  OPEN_PROMOTION: "OPEN_PROMOTION",
  // CLOSE_POPUP: "CLOSE_POPUP",
  // CAN_CASTLE: "CAN_CASTLE",
  // STALEMATE: "STALEMATE",
  // INSUFFICIENT_MATERIAL: "INSUFFICIENT_MATERIAL",
  WIN: "WIN",
  NEW_GAME: "NEW_GAME",
  // TAKE_BACK: "TAKE_BACK",
};

export default actionTypes;
